"""empty message

Revision ID: 1aeb58225ebf
Revises: aab4023388cb
Create Date: 2026-04-05 09:54:20.364071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aeb58225ebf'
down_revision = 'aab4023388cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('property_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=False))
        batch_op.drop_column('property_location')
        batch_op.drop_column('type_property')
        batch_op.drop_column('property_description')
        batch_op.drop_column('property_price')
        batch_op.drop_column('property_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_title', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type_property', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_location', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.drop_column('photo')
        batch_op.drop_column('property_type')
        batch_op.drop_column('price')
        batch_op.drop_column('location')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
