"""empty message

Revision ID: aab4023388cb
Revises: 
Create Date: 2026-04-05 06:47:03.210268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab4023388cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_title', sa.String(length=256), nullable=True),
    sa.Column('property_description', sa.String(length=256), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('property_location', sa.String(length=256), nullable=True),
    sa.Column('property_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type_property', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_details')
    # ### end Alembic commands ###
